services:
    converter_db:
        image: mysql:8.0
        container_name: file_converter_db
        restart: always
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            DB_MYSQL_HOST: converter_db
            MYSQL_DATABASE: conversions
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init-db:/docker-entrypoint-initdb.d


    backend:
        build: .
        container_name: converter_backend
        restart: always
        environment:
            - DB_HOST=converter_db
            - DB_PASSWORD=root
            - DB_NAME=conversions
        # Espera a que el servicio converter_db esté listo
        depends_on:
            - converter_db
        ports:
            - "5050:5050"

volumes:
    mysql_data: